config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  root 'home#index'

  resources :users, :path => 'usuarios_registrados' 
  resources :records, :path => 'registros'

  resources :people, :path => 'personas' do
    resources :records, :path => 'registros'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  get 'print_records', to: 'reports#records_xls'
  get 'print_people', to: 'reports#people_xls'
  get 'print_users', to: 'reports#users_xls'


  get 'reportes', to: 'reports#index'
  get 'reporte_usuarios', to: 'reports#users_pdf'
  get 'reporte_personas', to: 'reports#people_pdf'
  get 'reporte_registros', to: 'reports#records_pdf'

  get 'documentation', to: 'documentation#index'

end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id             :bigint           not null, primary key
#  name           :string
#  lastname       :string
#  phone          :integer
#  mail           :string
#  address        :string
#  identification :string
#  company        :string
#  user_id        :bigint           not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Person < ApplicationRecord
  # Relaciones
  belongs_to :user
  has_many :records


  # Nested de registros
  accepts_nested_attributes_for :records, allow_destroy: true, reject_if: :all_blank

  # Validaciones
  validates :name, presence: true
  validates :lastname, presence: true
  validates :phone, presence: true
  validates :address, presence: true
  validates :identification, presence: true
  
  #  Buscador
  def self.search_by(search_term)
    where(["(name) LIKE :search_term OR (lastname) LIKE :search_term OR
            (email) LIKE :search_term OR (company) LIKE :search_term OR
            (address) LIKE :search_term OR (identification)  LIKE :search_term ",{ search_term: "%#{search_term}%" }])
  end

  # Imprime en Csv
  require 'csv'
  def self.to_csv(options = {})
      CSV.generate(options) do |csv|
          csv << ['id', 'Nombres', 'Apellidos', 'Telefonos', 
                  'Email', 'Direcciones', 'Identificaciones', 'Empresas',
                  'Usuario que registro', 'Creado en', 'Actualizado en'] 
          all.each do |person|
              csv << [person.id, person.name, person.lastname,  person.phone, 
                      person.email, person.address, person.identification, person.company,        
                      person.user.email, person.created_at, person.updated_at] 
          end
      end
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! 

  def index
    @people = Person.all
    @people = Person.paginate(page: params[:page], per_page: 10)


    if params[:search].present?
      @search_term = params[:search]
      @people = @people.search_by(@search_term)
      if @people.size.zero?
        redirect_to new_person_path
      end
    end

  end

  def show
  end

  def new
    @person = Person.new
    @person.records.build # Metodo para nested
  end

  def edit
  end

  def create
    #@person = current_user.people.new(person_params)
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end




  private
    def set_person
      @person = Person.find(params[:id])
    end

    def person_params
      params.require(:person).permit(:name, :lastname, :phone, :email, :address, :identification, 
      :company, :user_id, records_attributes: [:id, :entrance_temperature, :departure_temperature])
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<div class="card mx-5 my-5 px-5 py-5">
    <h1 class="mb-3">Personas</h1>
    <%= simple_form_for(@person) do |f| %>
      <% if f.error_notification %>
        <div class="alert alert-warning" role="alert">
          Por favor revisa
        </div>
      <% end %>
      <div class="form-row mb-0">

        <div class="col-md-4 mb-3 form-group">
          <%= f.label :nombre, 'Nombre' %>
          <%= f.input :name, 
                      label: false,
                      required: true,
                      error: 'El nombre no es valido', 
                      :input_html => { :id => 'registro_temperatura_ingreso' } %>
        </div>
        <div class="col-md-4 mb-3 form-group">
          <%= f.label :lastname, 'Apellido' %>
          <%= f.input :lastname, 
                      label: false,
                      required: true,
                      error: 'El apellido no es valido', 
                      :input_html => { :id => 'registro_temperatura_salida' } %>
        </div>
        <div class="col-md-4 mb-3 form-group">
          <%= f.label :phone, 'Telefono' %>
          <%= f.input :phone, 
                      label: false,
                      required: true,
                      error: 'El telefono no es valido', 
                      :input_html => { :id => 'persona_telefono' } %>
        </div>
      </div>

      <div class="form-row">
        <div class="col-md-4 mb-3 form-group">
          <%= f.label :email, 'Email' %>
          <%= f.input :email, label: false %>
        </div>
        <div class="col-md-4 mb-3 form-group">
          <%= f.label :address, 'Direccion' %>  
          <%= f.input :address, 
            label: false,
            required: true,
            error: 'La direccion no es valida', 
            :input_html => { :id => 'persona_direccion' } %>
        </div>
        <div class="col-md-4 mb-3 form-group">
          <%= f.label :identification, 'Identificacion' %>
          <%= f.input :identification, 
            as: :numeric,
            label: false,
            required: true,
            error: 'La identificacion no es valida' %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-3 mb-3 form-group">
          <%= f.label :rol, 'Rol' %>
          <%= f.select :rol, options_for_select([ "Seleccion el rol de la persona","Empleado", "Visitante", "Contratista" ]), 
            {}, { class: "form form-group form-control", id: "person_rol", error: 'La identificacion no es valida' }  %>
          <div class="messages"></div>
        </div>
        <div class="col-md-3 mb-3 form-group">
          <%= f.label :company, 'Empresa',  class: "ocultame", id: "label_company" %>
          <%= f.input :company, label: false, :input_html => { class: "ocultame", id: "persona_empresa"} %>
          <div class="messages"></div>
        </div>
      </div>

      <!-- Enviar por defecto el usuario que registro a la persona -->
      <%= f.association :user, selected: current_user, input_html: { hidden: true }, label: false  %>

      <%= f.button :submit, 'Guardar', :id => "persona_guardar"  %>
      <%= link_to 'Atras', people_path, :class => "btn btn-info" %>

    <% end %>
  </div>

<script>
$(document).ready(function(){
    $("#person_rol").change(function(){
        var selectedCountry = $("#person_rol option:selected").text();
        if(selectedCountry == "Contratista" ){
              $('#label_company').removeClass('ocultame');
              $('#persona_empresa').removeClass('ocultame').val("");

        }
        else if(selectedCountry == "Visitante" ){
              $('#label_company').addClass( "ocultame" )
              $('#persona_empresa').addClass('ocultame').val("No aplica");

        }
        else if(selectedCountry == "Empleado" ){
              $('#label_company').addClass('ocultame');
              $('#persona_empresa').addClass('ocultame').val("Personal Propio");

        }
    });
});
</script>

app/views/people/_search.html.erb
<div class="container pt-5 mb-5 pb-2">
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="card text-center">
                <div class="card-header mdb-color blue-grey darken-2 white-text text-center py-3">
                    BUSCADOR
                </div>
                <div class="card-body px-lg-5 pt-4">
                    <%= form_tag people_path, method: :get do %>
                        <div class="form-row">
                            <div class="col-md-12 col-lg-10">
                                <div class="md-form">
                                    <%= text_field_tag :search, @search_term, class: "form-control", autocomplete: 'off' %>
                                </div>
                            </div>
                            <div class="col-md-12 col-lg-2">
                            <%= submit_tag "Buscar", class: "form-control" %>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/people/edit.html.erb
<%= render 'form', person: @person %>

app/views/people/index.html.erb
<div class="card">
  <h3 class="card-header text-center font-weight-bold text-uppercase py-4">Personas</h3>
  <div class="card-body">
    <div id="table" class="table-editable">

            <%= render 'search', person: @person %>

      <table class="table table-bordered table-responsive-md table-striped text-center">
        <thead>
          <tr>
            <th>Id</th>
            <th>Registros</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Telefono</th>
            <th>Email</th>
            <th>Direccion</th>
            <th>Identificacion</th>
            <th>Empresa</th>
            <th>Usuario</th>
            <th  colspan="3">Opciones</th>
          </tr>
        </thead>
        <tbody>
          <% @people.each do |person| %>

          <tr>
            <td><%= link_to  'Registros(' + person.records.count.to_s + ')', person_records_path(person) %></td>
            <td><%= person.id %></td>
            <td><%= person.name %></td>
            <td><%= person.lastname %></td>
            <td><%= person.phone %></td>
            <td><%= person.email %></td>
            <td><%= person.address %></td>
            <td><%= person.identification %></td>
            <td><%= person.company %></td>
            <td><%= person.user.email %></td>
            <td><%= link_to 'Mostrar', person, :class => "btn btn-info btn-sm" %></td>
            <td><%= link_to 'Editar', edit_person_path(person), :class => "btn btn-success btn-sm" %></td>
          </tr>
          <% end %>

        </tbody>
      </table>
    <div class="btn-group demoPadder" role="group" aria-label="Basic example">
      <%= link_to 'Nueva persona', new_person_path(@person), :class => "btn btn-primary" %>
      <%= link_to 'Atras', root_path, :class => "btn btn-secondary" %>
    </div>
    </div>
  </div>
  <div class="paginacion">
    <%= will_paginate @people, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
</div>

app/views/people/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
    xmlns:o="urn:schemas-microsoft-com:office:office"
    xmlns:x="urn:schemas-microsoft-com:office:excel"
    xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
    xmlns:html="http://www.w3.org/TR/REC-html40">
    <Worksheet ss:Name="Sheet1">
        <Table>
            <Row>
                <Cell><Data ss:Type="String">Id</Data></Cell>
                <Cell><Data ss:Type="String">Nombre</Data></Cell>
                <Cell><Data ss:Type="String">Apellido</Data></Cell>
                <Cell><Data ss:Type="String">Email</Data></Cell>
                <Cell><Data ss:Type="String">Telefono</Data></Cell>
                <Cell><Data ss:Type="String">Direccion</Data></Cell>
                <Cell><Data ss:Type="String">Identificacion</Data></Cell>
                <Cell><Data ss:Type="String">Empresa</Data></Cell>
                <Cell><Data ss:Type="String">Usuario</Data></Cell>
                <Cell><Data ss:Type="String">Creado en</Data></Cell>
                <Cell><Data ss:Type="String">Actualizado es</Data></Cell>
            </Row>
        <% @results2.each do |row| %>
            <Row>
                <Cell><Data ss:Type="String"><%= row["id"] %></Data></Cell>
                <Cell><Data ss:Type="String"><%= row["name"] %></Data></Cell>
                <Cell><Data ss:Type="String"><%= row["lastname"] %></Data></Cell>
                <Cell><Data ss:Type="String"><%= row["email"] %></Data></Cell>
                <Cell><Data ss:Type="String"><%= row["phone"] %></Data></Cell>
                <Cell><Data ss:Type="String"><%= row["address"] %></Data></Cell>
                <Cell><Data ss:Type="String"><%= row["identification"] %></Data></Cell>
                <Cell><Data ss:Type="String"><%= row["company"] %></Data></Cell>
                <Cell><Data ss:Type="String"><%= row["user_id"] %></Data></Cell>
                <Cell><Data ss:Type="String"><%= row["created_at"] %></Data></Cell>
                <Cell><Data ss:Type="String"><%= row["updated_at"] %></Data></Cell>
            </Row>
        <% end %>
        </Table>
    </Worksheet>
</Workbook>

app/views/people/new.html.erb
<%= render 'form', person: @person %>

app/views/people/print_people.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
    xmlns:o="urn:schemas-microsoft-com:office:office"
    xmlns:x="urn:schemas-microsoft-com:office:excel"
    xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
    xmlns:html="http://www.w3.org/TR/REC-html40">
    <Worksheet ss:Name="Sheet1">
        <Table>
            <Row>
                <Cell><Data ss:Type="String">Id</Data></Cell>
                <Cell><Data ss:Type="String">Nombre</Data></Cell>
                <Cell><Data ss:Type="String">Apellido</Data></Cell>
                <Cell><Data ss:Type="String">Email</Data></Cell>
                <Cell><Data ss:Type="String">Telefono</Data></Cell>
                <Cell><Data ss:Type="String">Direccion</Data></Cell>
                <Cell><Data ss:Type="String">Identificacion</Data></Cell>
                <Cell><Data ss:Type="String">Empresa</Data></Cell>
                <Cell><Data ss:Type="String">Usuario</Data></Cell>
                <Cell><Data ss:Type="String">Creado en</Data></Cell>
                <Cell><Data ss:Type="String">Actualizado es</Data></Cell>
            </Row>
        <% @results2.each do |row| %>
            <Row>
                <Cell><Data ss:Type="String"><%= row.id %></Data></Cell>
                <Cell><Data ss:Type="String"><%= row.name %></Data></Cell>
                <Cell><Data ss:Type="String"><%= row.lastname %></Data></Cell>
                <Cell><Data ss:Type="String"><%= row.email %></Data></Cell>
                <Cell><Data ss:Type="String"><%= row.phone %></Data></Cell>
                <Cell><Data ss:Type="String"><%= row.address %></Data></Cell>
                <Cell><Data ss:Type="String"><%= row.identification %></Data></Cell>
                <Cell><Data ss:Type="String"><%= row.company %></Data></Cell>
                <Cell><Data ss:Type="String"><%= row.user.name %></Data></Cell>
                <Cell><Data ss:Type="String"><%= row.created_at %></Data></Cell>
                <Cell><Data ss:Type="String"><%= row.updated_at %></Data></Cell>
            </Row>
        <% end %>
        </Table>
    </Worksheet>
</Workbook>

app/views/people/show.html.erb
<div class="container my-4">
   <div class="row">
      <div class="col-lg-12 col-md-12 mb-12">
         <div class="card card-cascade wider">
            <div class="card-body card-body-cascade text-center">
               <div class="alert alert-primary" role="alert">
                  <br/>
                  <h2 class="card-title"><strong>Información de la persona <%= icon('fa', 'user-friends') %> </strong></h2>
                  <br/>
               </div>
               <div class="container">
               <div class="row">
                  <div class="col-sm">
                  <div class="alert alert-secondary" role="alert">
                     <h5><b>Id:</b></h5>
                     <%= @person.id %>
                  </div>        
                  </div>
                  <div class="col-sm">
                  <div class="alert alert-secondary" role="alert">
                     <h5><b>Nombre:</b></h5>
                     <%= @person.name %>
                  </div>        
                  </div>
                  <div class="col-sm">
                  <div class="alert alert-secondary" role="alert">
                     <h5><b>Apellido:</b></h5>
                     <%= @person.lastname %>
                  </div>        
                  </div>
               </div>
               <div class="row">
                  <div class="col-sm">
                    <div class="alert alert-secondary" role="alert">
                      <h5><b>Telefono:</b></h5>
                      <%= @person.phone %>
                    </div>        
                    </div>
                    <div class="col-sm">
                    <div class="alert alert-secondary" role="alert">
                      <h5><b>Email:</b></h5>
                      <%= @person.email %>
                    </div>        
                    </div>
                    <div class="col-sm">
                    <div class="alert alert-secondary" role="alert">
                      <h5><b>Direccion:</b></h5>
                      <%= @person.address %>
                    </div>        
                  </div>
               </div>

               <div class="row">
                  <div class="col-sm">
                    <div class="alert alert-secondary" role="alert">
                      <h5><b>Identificacion:</b></h5>
                      <%= @person.identification %>
                    </div>        
                    </div>
                    <div class="col-sm">
                    <div class="alert alert-secondary" role="alert">
                      <h5><b>Empresa:</b></h5>
                      <%= @person.company %>
                    </div>        
                    </div>
                    <div class="col-sm">
                    <div class="alert alert-secondary" role="alert">
                      <h5><b>Usuario que lo registro:</b></h5>
                      <%= @person.user.email %>
                    </div>        
                  </div>
               </div>
              
               <%= link_to 'Editar', edit_person_path(@person), class: "btn btn-success" %> 
               <%= link_to 'Atras', people_path, class: "btn btn-info" %>
               <!-- Button trigger modal -->
               <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
               Reporte
               </button>
               </div>    
            </div>
         </div>
      </div>
   </div>
</div>




<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Numero de registros de <%= @person.email %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
         <%= pie_chart @person.records.group(:person_id).count %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>