config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  root 'home#index'

  resources :users, :path => 'usuarios_registrados' 
  resources :records, :path => 'registros'

  resources :people, :path => 'personas' do
    resources :records, :path => 'registros'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  get 'print_records', to: 'reports#records_xls'
  get 'print_people', to: 'reports#people_xls'
  get 'print_users', to: 'reports#users_xls'


  get 'reportes', to: 'reports#index'
  get 'reporte_usuarios', to: 'reports#users_pdf'
  get 'reporte_personas', to: 'reports#people_pdf'
  get 'reporte_registros', to: 'reports#records_pdf'

  get 'documentation', to: 'documentation#index'

end

app/models/record.rb
class Record < ApplicationRecord
  # Relaciones
  belongs_to :person

  # Validaciones
  validates :entrance_temperature, 
            presence: true, 
            length: {  minimum: 4, maximum: 4 }, 
            numericality: {  greater_than_or_equal_to: 32, less_than_or_equal_to: 42 }

  validates :departure_temperature, 
            presence: true, 
            length: {  minimum: 4, maximum: 4 }, 
            numericality: {  greater_than_or_equal_to: 32, less_than_or_equal_to: 42 }

  # Buscador
  def self.search_by(search_term)
    where("Date(created_at) = :search_term", { search_term: "%#{search_term}%" })
  end

  # Imprime en Csv
  require 'csv'
  def self.to_csv(options = {})
      CSV.generate(options) do |csv|
          csv << ['id', 'Persona', 'Temperatura de ingreso', 'Temperatura de salida', 'Creado en', 'Actualizado en'] 
          all.each do |record|
              csv << [record.id, record.person.email, record.entrance_temperature, record.departure_temperature, record.created_at, record.updated_at] 
          end
      end
  end


end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  before_action :authenticate_user! 



  def index
    @records = @person.records.paginate(page: params[:page], per_page: 10)


    #  Buscador por fecha de registro
    if params[:search].present?
      @search_term = params[:search]
      @records = @records.search_by(@search_term)
    end

   
  end

  def show

  end

  def new
    @record = Record.new
  end

  def edit
  end

  def create

    @record = Record.new(record_params)
    @record.person_id = @person.id

    respond_to do |format|
      if @record.save
        format.html { redirect_to person_records_path(@person,@record), notice: 'Registro was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to person_records_path(@person,@record), notice: 'Registro was successfully created.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to person_records_path(@person), notice: 'record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_record
      @person = Person.find(params[:person_id])
      @record = Record.find(params[:id]) if params[:id]    
   end

    def record_params
      params.require(:record).permit(:entrance_temperature, :departure_temperature, :person_id)
    end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<div class="card mx-5 my-5 px-5 py-5">
  <h1 class="mb-3">Registro <%= @record.id %> de <%= @person.name %></h1>
  <%= simple_form_for [@person,@record], :html => { :class => 'form-horizontal' } do |f| %>

    <% if f.error_notification %>
      <div class="alert alert-warning" role="alert">
        Por favor revisa
      </div>
    <% end %>

    <div class="form-row mb-0">
      <div class="col-md-6 form-group">
        <%= f.label :entrance_temperature, 'Temperatura de ingreso' %>
        <%= f.input :entrance_temperature,
            error: 'La temperatura no es valida', 
            required: true, 
            input_html: { min: '0', step: 'any', :id => 'registro_temperatura_ingreso' }, 
            label: false %>
      </div>
      <div class="col-md-6 form-group">
        <%= f.label :departure_temperature, 'Temperatura de salida' %>
        <%= f.input :departure_temperature, 
            error: 'La temperatura no es valida', 
            required: true, 
            input_html: { min: '0', step: 'any', :id => 'registro_temperatura_salida' },
            label: false %>
      </div>
      <div class="col-md-4 form-group">
        <div class="input-group">
          <%= f.association :person, selected: @person.id, input_html: { hidden: true }, label: false  %>
          <div class="messages w-100"></div>
        </div>
      </div>
    </div>

    <%= f.button :submit, 'Guardar', :id => "registro_guardar" %>
    <%= link_to 'Atras', person_records_path(@person), :class => "btn btn-info" %>

  <% end %>
</div>

app/views/records/_search.html.erb
<div class="container pt-5 mb-5 pb-2">
	<div class="row justify-content-center">
		<div class="col-12">
			<div class="card text-center">

				<div class="card-header mdb-color blue-grey darken-2 white-text text-center py-3">
						BUSCADOR
				</div>
			
				<div class="card-body px-lg-5 pt-4">
					<%= form_tag person_records_path(@person), method: :get do %>
						<div class="form-row">
							<div class="col-md-12 col-lg-10">
								<div class="md-form">
										<%= text_field_tag :search, @search_term, class: "form-control", autocomplete: 'off',
										id: "datepicker" %>
								</div>
							</div>
							<div class="col-md-12 col-lg-2">
							<%= submit_tag "Buscar", class: "form-control" %>
							</div>
						</div>
					<% end %>
				</div>
				
			</div>
		</div>
	</div>
</div>

app/views/records/edit.html.erb
<%= render 'form', record: @record %>

app/views/records/index.html.erb
<div class="card">
  <h3 class="card-header text-center font-weight-bold text-uppercase py-4">Registros del <%= @person.name %></h3>
  <div class="card-body">
    <div id="table" class="table-editable">
      <%= render 'search', record: @record %>

      <table class="table table-bordered table-responsive-md table-striped text-center">
        <thead>
          <tr>
            <th>Id</th>
            <th>Temperatura Ingreso</th>
            <th>Temperatura Salida</th>
            <th>Persona que registro</th>
            <th>Fecha</th>
            <th  colspan="3">Opciones</th>
          </tr>
        </thead>
        <tbody>
          <% @records.each do |record| %>
            <tr>
              <td><%= record.id %></td>
              <td class="entrada"><%= record.entrance_temperature %></td>
              <td class="entrada"><%= record.departure_temperature %></td>
              <td><%= record.person.email %></td>
              <td><%= record.created_at.strftime("%d-%m-%Y %H:%M") %></td>
              <td><%= link_to 'Mostrar',  person_record_path(@person,record), :class => "btn btn-info btn-sm" %></td>
              <td><%= link_to 'Editar',  edit_person_record_path(@person,record), :class => "btn btn-success btn-sm" %></td>
              <td><%= link_to 'Eliminar', person_record_path(@person,record), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-sm" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
        
      <div class="btn-group demoPadder" role="group" aria-label="Basic example">
        <%= link_to 'Nuevo Registro', new_person_record_path(@person), :class => "btn btn-primary" %>
        <%= link_to 'Atras', people_path, :class => "btn btn-secondary" %>
      </div>
    </div>
  </div>
  <div class="paginacion">
    <%= will_paginate @records, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
</div>

app/views/records/new.html.erb
<%= render 'form', record: @record %>

app/views/records/show.html.erb
<div class="container my-4">
	<div class="row">
		<div class="col-lg-12 col-md-12 mb-12">
			<div class="card card-cascade wider">
				<div class="card-body card-body-cascade text-center">
					<div class="alert alert-primary" role="alert">
						<br/>
							<h2 class="card-title"><strong>Registro de <%= @record.person.email %> <i class="fas fa-paste"></i> </strong></h2>
						<br/>
					</div>
					<div class="container">
						<div class="row">
							<div class="col-sm">
								<div class="alert alert-secondary" role="alert">
									<h5><b>Id:</b></h5>
									<%= @record.id %>
								</div>        
							</div>
							<div class="col-sm">
								<div class="alert alert-secondary" role="alert">
									<h5><b>Temperatura Ingreso:</b></h5>
									<%= @record.entrance_temperature %>
								</div>        
							</div>
							<div class="col-sm">
								<div class="alert alert-secondary" role="alert">
									<h5><b>Temperatura Egreso:</b></h5>
									<%= @record.departure_temperature %>
								</div>        
							</div>
						</div>
						<%= link_to 'Editar',edit_person_record_path(@person,@record), :class => 'btn btn-success' %>
						<%= link_to 'Atras', person_records_path(@person), :class => 'btn btn-info' %>
					</div>    
				</div>
			</div>
		</div>
	</div>
</div>