config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  root 'home#index'

  resources :users, :path => 'usuarios_registrados' 
  resources :records, :path => 'registros'

  resources :people, :path => 'personas' do
    resources :records, :path => 'registros'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  get 'print_records', to: 'reports#records_xls'
  get 'print_people', to: 'reports#people_xls'
  get 'print_users', to: 'reports#users_xls'


  get 'reportes', to: 'reports#index'
  get 'reporte_usuarios', to: 'reports#users_pdf'
  get 'reporte_personas', to: 'reports#people_pdf'
  get 'reporte_registros', to: 'reports#records_pdf'

  get 'documentation', to: 'documentation#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    # Metodo que redirecciona al index de cancan
    rescue_from CanCan::AccessDenied do |exception|
        redirect_to root_path, :alert => exception.message
    end

    # Metodo que ayuda a guardar los parametros de el sign_up
    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :user_role) }
    end

end

app/helpers/application_helper.rb
# app/helpers/application_helper.rb
module ApplicationHelper

    # This method creates a link with `data-id` `data-fields` attributes. These attributes are used to create new instances of the nested fields through Javascript.
    def link_to_add_fields(name, f, association)

        # Takes an object (@person) and creates a new instance of its associated model (:addresses)
        # To better understand, run the following in your terminal:
        # rails c --sandbox
        # @person = Person.new
        # new_object = @person.send(:addresses).klass.new
        new_object = f.object.send(association).klass.new

        # Saves the unique ID of the object into a variable.
        # This is needed to ensure the key of the associated array is unique. This is makes parsing the content in the `data-fields` attribute easier through Javascript.
        # We could use another method to achive this.
        id = new_object.object_id

        # https://api.rubyonrails.org/ fields_for(record_name, record_object = nil, fields_options = {}, &block)
        # record_name = :addresses
        # record_object = new_object
        # fields_options = { child_index: id }
            # child_index` is used to ensure the key of the associated array is unique, and that it matched the value in the `data-id` attribute.
            # `person[addresses_attributes][child_index_value][_destroy]`
        fields = f.fields_for(association, new_object, child_index: id) do |builder|

            # `association.to_s.singularize + "_fields"` ends up evaluating to `address_fields`
            # The render function will then look for `views/people/_address_fields.html.erb`
            # The render function also needs to be passed the value of 'builder', because `views/people/_address_fields.html.erb` needs this to render the form tags.
            render(association.to_s.singularize + "_fields", f: builder)
        end

        # This renders a simple link, but passes information into `data` attributes.
            # This info can be named anything we want, but in this case we chose `data-id:` and `data-fields:`.
        # The `id:` is from `new_object.object_id`.
        # The `fields:` are rendered from the `fields` blocks.
            # We use `gsub("\n", "")` to remove anywhite space from the rendered partial.
        # The `id:` value needs to match the value used in `child_index: id`.
        link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})

    end
end

app/views/application/_breadcrumb.html.erb
<div class="app-breadcrumb container">
  <div class="d-flex flex-row justify-content-between">
    <ol class="breadcrumb bg-transparent px-0">
      <%= yield :breadcrumb %>
    </ol>

    <div>
      <button type="button" class="btn btn-sm btn-outline-secondary mt-2 mr-2 d-none" data-tooltip data-placement="bottom" data-trigger="hover" title="compare by clicking fast" data-toggle="button" aria-pressed="false" autocomplete="off">
        Swap
      </button>

      <div class="btn-group btn-group-toggle mt-2 d-none" data-toggle="buttons">
        <label class="btn btn-sm btn-outline-secondary">
          <input type="radio" name="view" id="stack" autocomplete="off"> Stack
        </label>
        <label class="btn btn-sm btn-outline-secondary active">
          <input type="radio" name="view" id="split" autocomplete="off" checked> Split
        </label>
      </div>
    </div>
  </div>
</div>

app/views/application/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <i class="fas fa-head-side-mask"></i>&nbsp;<%= link_to('CoronaSafe', root_path, :class => "navbar-brand")  %>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <%= link_to('Usuarios', users_path, :class => "nav-link") %>
      </li>
      <li class="nav-item active">
        <%= link_to('Personas', people_path, :class => "nav-link") %>
      </li>
      <li class="nav-item active">
        <%= link_to('Reportes', reportes_path, :class => "nav-link") %>
      </li>
    </ul>
    <ul class="my-2 my-lg-0">
      <div class="dropdown show opciones_usuario">
        <a class="btn btn-info dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Opciones
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <% if user_signed_in? %>
            <%= link_to('Editar', edit_user_registration_path, :class => "dropdown-item") %>
          <%= link_to("Salir", destroy_user_session_path, :confirm => "Are you sure?", :class => "dropdown-item") %>

          <% else %>
            <%= link_to('Registrar', new_user_registration_path, :class => "dropdown-item")  %>
            <%= link_to('Ingresar', new_user_session_path, :class => "dropdown-item")  %> 
          <% end %>
        </div>
      </div>
    </ul>
  </div>
</nav>

app/views/application/_jumbotron.html.erb
<section class="app-jumbotron jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Simple Form 💜 Bootstrap 4</h1>
    <p class="lead text-muted">
      Build responsive, mobile-first HTML Forms with <a href="https://github.com/heartcombo/simple_form">Simple Form</a> and <a href="http://getbootstrap.com/">Bootstrap</a>.
      The world's most popular front-end component library meets easy and simple DSL to build Forms with Rails.
    </p>
    <p>
      <%= link_to "Example", new_examples_vertical_path, class: "btn btn-primary px-4 mx-2" %>
      <%= link_to "Documentation", documentation_path, class: "btn btn-secondary px-4 mx-2" %>
    </p>
  </div>
</section>

app/views/application/_welcome.html.erb
  <div class="jumbotron">
        <div class="container">
          <h1 class="display-5 text-justify">PRIMER PROGRAMA PARA CONTROLAR LOS INGRESOS Y EGRESOS DE UNA PERSONA O DE UN NEGOCIO!</h1>
          <p>Evita contagios dentro de tu empresa y manten el control de quien ingresa y sale de tu negocio</p>
          <p><a class="btn btn-primary btn-lg" href="#" role="button">Ver más »</a></p>
        </div>
      </div>
  
  
    <div class="album py-5 bg-light">
    
      <div class="container">
        <hr class="my-4">
        <div class="row">
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <i class="fas fa-chart-bar"></i>
              <div class="card-body">
                <h4 class="card-title">Reportes</h4>
                <p class="card-text text-justify">Imprime reportes detallados en varios formatos de las personas que entran y salen de su negocio, durante un periodo de tiempo predeterminado
</p>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <i class="fas fa-thermometer-three-quarters"></i>
              <div class="card-body">
                <h4 class="card-title">Alarma</h4>
                <p class="card-text text-justify">Alerta en caso de que se haya generado algun registro de una persona que tenga fiebre, con todos los datos de la perona que presento esta sintomatología.</p>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <i class="fas fa-user-check"></i>
              <div class="card-body">
                <h4 class="card-title">Integridad</h4>
                <p class="card-text text-justify">Permite registrar una persona una sola vez y pueda tener muchos registros y llevar el control de ellos y guardarlos de forma segura en la nube.</p>
              </div>
            </div>
          </div>
          
        </div>
        <hr class="my-4">
        <div class="row">
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <i class="fas fa-search"></i>
              <div class="card-body">
                <h4 class="card-title">Diseño amigable</h4>
                <p class="card-text text-justify">Facil acceso para clientes ya registrados, por medio de un buscador en la pagina principal</p>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <i class="fas fa-mobile-alt"></i>
              <div class="card-body">
                <h4 class="card-title">Responsive web</h4>
                <p class="card-text text-justify">Diseño responsive que permite trabajar desde dispositivos moviles.</p>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <i class="fas fa-check-square"></i>
              <div class="card-body">
                <h4 class="card-title">Mantenimiento</h4>
                <p class="card-text text-justify">Constantes actualizaciones para la seguridad e integridad de la informacion.</p>
              </div>
            </div>
          </div>
          
        </div>
        <hr class="my-4">
      </div>
    </div>





<div class="my-4">

  <!-- Footer -->
  <footer class="page-footer font-small teal pt-4">
      <div class="container">

    <!-- Footer Links -->
    <div class="container-fluid text-center text-md-left">

      <!-- Grid row -->
      <div class="row">
      
        <!-- Grid column -->
        <div class="col-md-6 mt-md-0 mt-3">
          <!-- Content -->
          <h5 class="text-uppercase">Redes Sociales</h5>
          <div class="col-md-12 py-5">
            <div class="mb-5 flex-center">
              <!-- Facebook -->
              <a class="fb-ic">
                <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
              </a>
              <!-- Twitter -->
              <a class="tw-ic">
                <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
              </a>
              <!-- Google +-->
              <a class="gplus-ic">
                <i class="fab fa-google-plus-g fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
              </a>
              <!--Linkedin -->
              <a class="li-ic">
                <i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
              </a>
              <!--Instagram-->
              <a class="ins-ic">
                <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
              </a>
              <!--Pinterest-->
              <a class="pin-ic">
                <i class="fab fa-pinterest fa-lg white-text fa-2x"> </i>
              </a>
            </div>
          </div>
        </div>
        <!-- Grid column -->

        <hr class="clearfix w-100 d-md-none pb-3">

        <!-- Grid column -->
        <div class="col-md-3 mb-md-0 mb-3">

          <!-- Links -->
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled">
            <li>
              <a href="#!">Link 1</a>
            </li>
            <li>
              <a href="#!">Link 2</a>
            </li>
            <li>
              <a href="#!">Link 3</a>
            </li>
            <li>
              <a href="#!">Link 4</a>
            </li>
          </ul>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 mb-md-0 mb-3">

          <!-- Links -->
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled">
            <li>
              <a href="#!">Link 1</a>
            </li>
            <li>
              <a href="#!">Link 2</a>
            </li>
            <li>
              <a href="#!">Link 3</a>
            </li>
            <li>
              <a href="#!">Link 4</a>
            </li>
          </ul>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row -->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2018 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/"> MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
    </div>

  </footer>
  <!-- Footer -->