config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  root 'home#index'

  resources :users, :path => 'usuarios_registrados' 
  resources :records, :path => 'registros'

  resources :people, :path => 'personas' do
    resources :records, :path => 'registros'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  get 'print_records', to: 'reports#records_xls'
  get 'print_people', to: 'reports#people_xls'
  get 'print_users', to: 'reports#users_xls'


  get 'reportes', to: 'reports#index'
  get 'reporte_usuarios', to: 'reports#users_pdf'
  get 'reporte_personas', to: 'reports#people_pdf'
  get 'reporte_registros', to: 'reports#records_pdf'

  get 'documentation', to: 'documentation#index'

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user! 

  def index
  end


  # Reporte de usuarios
  # Pdf
  def users_pdf
    @users = User.all
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "users.html.erb",
        template: "users.html.erb"
      end
     end
  end
  # Xls
  def users_xls
    @results = User.all
        respond_to do |format|
      format.html
      format.csv { send_data User.to_csv }
      format.xls do
        render xls: "users.xls.erb",
        template: "users.xls.erb"
      end
    end
  end


  
  # Reporte de personas
  # Pdf
  def people_pdf
    @people = Person.all
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "people.html.erb",
        template: "people.html.erb"
      end
     end
  end
  # Xls
  def people_xls
    @results2 = Person.all
    respond_to do |format|
      format.csv { send_data Person.to_csv }
      format.xls do
        render xls: "people.xls.erb",
        template: "people.xls.erb"
      end
    end
  end



  # Reporte de movimientos
  # Pdf
  def records_pdf
    @records = Record.all
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "records.html.erb",
        template: "records.html.erb"
      end
     end
  end

  # Xls
  def records_xls
    @results3 = Record.all
    respond_to do |format|
      format.csv { send_data Record.to_csv }
      format.xls do
        render xls: "records.xls.erb",
        template: "records.xls.erb"
      end
    end
  end



end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/index.html.erb
<br/>
<div class="d-flex justify-content-center">
   <div class="btn-group demoPadder" role="group" aria-label="Basic example">
      <%= link_to "Usuarios Pdf", reporte_usuarios_path(format: "pdf"), target: "_blank", :class => "btn btn-primary" %>
      <%= link_to "Registros Pdf", reporte_registros_path(format: "pdf"), target: "_blank", :class => "btn btn-primary" %>
      <%= link_to "Personas Pdf", reporte_personas_path(format: "pdf"), target: "_blank", :class => "btn btn-primary" %>
   </div>
</div>
<br/>

<div class="d-flex justify-content-center">
   <div class="btn-group demoPadder" role="group" aria-label="Basic example">
      <%= link_to "Usuarios Csv", print_users_path(format: "csv"), target: "_blank", :class => "btn btn-primary" %>
      <%= link_to "Usuarios Xls", print_users_path(format: "xls"), target: "_blank", :class => "btn btn-primary" %>
   </div>
</div>
<br/>
<div class="d-flex justify-content-center">
   <div class="btn-group demoPadder" role="group" aria-label="Basic example">
      <%= link_to "Personas Csv", print_people_path(format: "csv"), target: "_blank", :class => "btn btn-primary" %>
      <%= link_to "Personas Xls", print_people_path(format: "xls"), target: "_blank", :class => "btn btn-primary" %>
   </div>
</div>
<br/>

<div class="d-flex justify-content-center">
   <div class="btn-group demoPadder" role="group" aria-label="Basic example">
      <%= link_to "Registros Csv", print_records_path(format: "csv"), target: "_blank", :class => "btn btn-primary" %>
      <%= link_to "Registros Xls", print_records_path(format: "xls"), target: "_blank", :class => "btn btn-primary" %>
   </div>
</div>
<br/>


<div class="container my-2">
   <div class="row">
      <div class="col-lg-6 col-md-4 mb-12">
         <div class="card card-cascade wider">
            <div class="card-body card-body-cascade text-center">
               <div class="alert alert-primary" role="alert">
                  <h2 class="card-title"><strong>Registro por dia  </strong></h2>
               </div>
               <div class="container">
               <div class="row">
                  <div class="col-sm">
                  <div class="alert alert-secondary" role="alert">
                  <%= pie_chart Record.group_by_day(:created_at).count  %>
                  </div>        
                  </div>
               </div>
               </div>    
            </div>
         </div>
      </div>
      <div class="col-lg-6 col-md-4 mb-12">
         <div class="card card-cascade wider">
            <div class="card-body card-body-cascade text-center">
               <div class="alert alert-primary" role="alert">
                  <h2 class="card-title"><strong>Registro al mes  </strong></h2>
               </div>
               <div class="container">
               <div class="row">
                  <div class="col-sm">
                  <div class="alert alert-secondary" role="alert">
                  <%= column_chart Record.group_by_month(:created_at, format: "%a").count %>
                  </div>        
                  </div>
               </div>
               </div>    
            </div>
         </div>
      </div>
   </div>
</div>


<div class="container my-2">
   <div class="row">
      <div class="col-lg-6 col-md-4 mb-12">
         <div class="card card-cascade wider">
            <div class="card-body card-body-cascade text-center">
               <div class="alert alert-primary" role="alert">
                  <h2 class="card-title"><strong>Personas registradas por dia  </strong></h2>
               </div>
               <div class="container">
               <div class="row">
                  <div class="col-sm">
                  <div class="alert alert-secondary" role="alert">
                  <%= pie_chart Person.group_by_day(:created_at).count  %>
                  </div>        
                  </div>
               </div>
               </div>    
            </div>
         </div>
      </div>
      <div class="col-lg-6 col-md-4 mb-12">
         <div class="card card-cascade wider">
            <div class="card-body card-body-cascade text-center">
               <div class="alert alert-primary" role="alert">
                  <h2 class="card-title"><strong>Registro de personas al mes  </strong></h2>
               </div>
               <div class="container">
               <div class="row">
                  <div class="col-sm">
                  <div class="alert alert-secondary" role="alert">
                  <%= column_chart Person.group_by_month(:created_at, format: "%a").count %>
                  </div>        
                  </div>
               </div>
               </div>    
            </div>
         </div>
      </div>
   </div>
</div>

<div class="container my-2">
   <div class="row">
      <div class="col-lg-6 col-md-4 mb-12">
         <div class="card card-cascade wider">
            <div class="card-body card-body-cascade text-center">
               <div class="alert alert-primary" role="alert">
                  <h2 class="card-title"><strong>Usuarios registrados por dia  </strong></h2>
               </div>
               <div class="container">
               <div class="row">
                  <div class="col-sm">
                  <div class="alert alert-secondary" role="alert">
                  <%= pie_chart User.group_by_day(:created_at).count  %>
                  </div>        
                  </div>
               </div>
               </div>    
            </div>
         </div>
      </div>
      <div class="col-lg-6 col-md-4 mb-12">
         <div class="card card-cascade wider">
            <div class="card-body card-body-cascade text-center">
               <div class="alert alert-primary" role="alert">
                  <h2 class="card-title"><strong>Usuarios registrados al mes  </strong></h2>
               </div>
               <div class="container">
               <div class="row">
                  <div class="col-sm">
                  <div class="alert alert-secondary" role="alert">
                  <%= column_chart User.group_by_month(:created_at, format: "%a").count %>
                  </div>        
                  </div>
               </div>
               </div>    
            </div>
         </div>
      </div>
   </div>
</div>




<div class="container my-2">
   <div class="row">
      <div class="col-lg-6 col-md-4 mb-12">
         <div class="card card-cascade wider">
            <div class="card-body card-body-cascade text-center">
               <div class="alert alert-danger" role="alert">
                  <h2 class="card-title"><strong>Registros con fiebre  </strong></h2>
               </div>
               <div class="container">
               <div class="row">
                  <div class="col-sm">
                  <div class="alert alert-secondary" role="alert">
                  <%= pie_chart Record.group(:entrance_temperature).where("entrance_temperature > 38 or departure_temperature > 38").count %>
                  </div>        
                  </div>
               </div>
               </div>    
            </div>
         </div>
      </div>

   </div>
</div>